# Generated by Django 4.0.6 on 2023-01-03 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 20, 43, 37, 584893)),
        ),
    ]
