# Generated by Django 4.0.6 on 2023-01-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 11, 19, 42, 12819)),
        ),
    ]
