# Generated by Django 4.0.6 on 2022-07-30 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
