# Generated by Django 4.0.6 on 2022-10-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='time_to_dilivery',
            new_name='time_to_delivery',
        ),
    ]
